services:
  db:
    image: postgres:latest
    container_name: helm_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - helm_db_data:/var/lib/postgresql
    restart: on-failure

volumes:
  helm_db_data:
